# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  
  frontend:
    image: frontend:1.0
    ports:
    - "3000:3000"
    restart: always
    environment:
      NODE_ENV: development
      REACT_APP_BUCKET_NAME: chat-app
      REACT_APP_BUCKET_ENDPOINTS: http://shivaantainfotech.com:9000
      REACT_APP_BACKEND_URL: http://shivaantainfotech.com:5000
  
  backend:
    image: backend:1.0
    ports:
    - "5000:5000"
    restart: always
    environment:
      COOKIE_EXPIRE: 5
      JWT_EXPIRE: 5d
      JWT_SECRET_KEY: fhsbdjfsbfshvbsvsvbshbsfsdcbgdgfdgdg
      DATABASE_URL: mongodb://admin:admin@mongo:27017/chat-app?authSource=admin&retryWrites=true&w=majority
      PORT: 5000
      REACT_APP_FRONTEND_URL: http://shivaantainfotech.com:3000    

volumes:
  minio-data: